# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c

cache:
  directories:
    - /Application/Unity/
    - /home/travis/.rvm/

osx_image: xcode61
rvm:
- 2.1.2

before_install:
- chmod +x Scripts/install.sh
install:
- ./Scripts/install.sh

after_success:
- "curl --ftp-create-dirs -T build.zip -u zetya96:Sajtoscsiga96 ftp://files.000webhost.com/public_html/build.zip -v"
script:
- ./Scripts/build.sh
