# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c

cache:
  directories:
    - /Application/Unity/
    - /home/travis/.rvm/

osx_image: xcode61
rvm:
- 2.1.2

before_install:
- chmod +x Scripts/install.sh
install:
- ./Scripts/install.sh

deploy:
  provider: releases
  api_key:
    secure: "b9604e4f3ab65c16e65f290b939d574b8fb6fd8c"
  file: "zipped.zip"
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: foltandaniel/projekteszkozok
script:
- ./Scripts/build.sh
